#!/bin/sh

set -e

export PORT=8000
# ngrok http ${PORT} > /dev/null &
ngrok http ${PORT} &

sleep 1

export URL=$(curl -s 'http://127.0.0.1:4040/api/tunnels' | jq -r '.tunnels[0].public_url' | sed -e 's/http:/https:/')

echo""
echo "App can be accessed via: $URL"

python app/main.py
